name: docker_wsl

services:
  nginx:
    image: nginx:alpine
    ports:
      - "4000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    container_name: nginx

  php:
    build: ./docker/php
    user: "1000:1000"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: app
      DB_USERNAME: app
      DB_PASSWORD: secret
    container_name: php-fpm

  node:
    image: node:20-alpine
    user: "1000:1000"
    working_dir: /app
    ports:
    - "4173:4173"
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run dev"
    tty: true
    container_name: node

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306" # ← ホストからも触りたい場合
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
      TZ: Asia/Tokyo
    volumes:
      - mysql-data:/var/lib/mysql
    container_name: mysql

volumes:
  mysql-data:
